spring.application.name=trailer
server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/trailer_system
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Set global logging level
logging.level.root=INFO

# Set logging level for a specific package
logging.level.com.system.trailer=DEBUG

# Customize log pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n